
### get all persons
GET http://localhost:3001/api/persons

### info page
GET http://localhost:3001/api/info


### get 1 person
GET http://localhost:3001/api/persons/2


### delete a person
DELETE http://localhost:3001/api/persons/3

### add a person
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Lluvi",
    "number": "123"

}
