
### get all persons
GET https://fullstackopen-ts2k.onrender.com/api/persons

### info page
GET https://fullstackopen-ts2k.onrender.com/api/info


### get 1 person
GET https://fullstackopen-ts2k.onrender.com/api/persons/2


### delete a person
DELETE https://fullstackopen-ts2k.onrender.com/api/persons/3

### add a person
POST  https://fullstackopen-ts2k.onrender.com/api/persons
Content-Type: application/json

{
    "name":"Lluvi",
    "number": "123"

}
